---
description: 指定选择UI
---

# 2.10 提示用户界面选择

## 用户选择工作流程

有时我们可能会构建一个通用工具，要求用户选择文档中的Revit元素（例如，元素重新编号工具）。这将需要无限数量的可自定义过滤器，以使用户能够使用逻辑选择他们选择的元素，但是我们可以通过提示用户选择某些内容来跳过整个问题。

## ISelectionFilter接口

**ISelectionFilter** 可以限制用户可以选择的元素种类。只需要创建一个实现该接口的新类。

然后，将此类的实例作为参数提供给 **PickElementsByRectangle()** 方法。例如，提示用户选择Walls所需的代码为：

```python
# 加载过滤选择的接口 ISelectionFilter
from Autodesk.Revit.UI.Selection import ISelectionFilter

# 定义选择过滤器
class MySelectionFilter(ISelectionFilter):
    def __init__(self):
        pass
    def AllowElement(self, element):
        return element.Category.Name == "墙"
    def AllowReference(self, element):
        return False

selection_filter = MySelectionFilter()                            # 仅选择墙
walls = uidoc.Selection.PickElementsByRectangle(selection_filter) # 返回框选的墙体
OUT = walls
```
