---
description: Dynamo geometry and Revit geometry might seem similar but are different!
---

# 2.6 几何(Geometry)转换

## Revit几何图形和Dynamo几何图形

Dynamo具有与Revit并行的类库。意味着需要使用特殊的转换方法来使两者之间进行转换实现数据交互。前面章节也提到过需要展开对象。

## 转换方式

您可以使用Dynamo API的转换方法轻松地在Dynamo和Revit几何类型之间进行切换:

* **ToProtoType()**
* **ToDSType()**
* **ToLine()**
* **ToPoint()**
* **ToVector()**
* **ToXyz()**

## Points

Revit点在3D空间中由其X，Y和Z坐标定义。创建方法：先创建点的对象 **Autodesk.Revit.DB.XYZ**，在创建Revit点 **Autodesk.Revit.DB.Point.Create** 方法创建，该方法需要传入点的对象。

```C#
XYZ revit_xyz = new Autodesk.Revit.DB.XYZ(0,0,0) // 创建点对象
Point revit_point = Autodesk.Revit.DB.Point.Create(revit_xyz) // 创建点
```

要创建Dynamo点，我们需要使用Designscript库，该库是Dynamo的一部分。Dynamo点的类型为 **Autodesk.DesignScript.Geometry.Point** 如果从Python节点输出以下dynamo_point，它将立即显示在Dynamo的3D背景预览中。

```python
dynamo_point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0,0,0) # 创建点
OUT = dynamo_point  # 输出点视图将显示
```

* 注意：即使我们在这里创建Revit对象，在这种情况下，也不需要将它们包装在 **Transaction** 事务中。

```python
revit_xyz = Autodesk.Revit.DB.XYZ(0,0,0) # Revit XYZ
# 使用XYZ对象创建点
revit_point = Autodesk.Revit.DB.Point.Create(revit_xyz)
OUT = revit_xyz, revit_point
```

我们可以从Python脚本节点输出XYZ和Point，但是除非将它们转换为Dynamo类型，否则它们将在Dynamo几何预览中不可见： *ToPoint() ToProtoType()*

```python
revit_xyz = Autodesk.Revit.DB.XYZ(0,0,0)
revit_point = Autodesk.Revit.DB.Point.Create(revit_xyz)
OUT = revit_xyz.ToPoint(), revit_point.ToProtoType()
```

## Lines / Curves

​​先看一下Dynamo类：Dynamo有两个**线型**几何类。了解他们之间存在区别。

* **Autodesk.DesignScript.Geometry.Line** 线段，具有起点和终点。
* **Autodesk.DesignScript.Geometry.Curve** 复杂的曲面或UV坐标。Dynamo的 **Curve** 类包含 **Line** 。

为了使这个示例简单，我们将在下面显示如何创建一条简单的Dynamo行。首先，我们将创建Dynamo点，然后将其用作定义直线的起点和终点。

```python
dynamo_point_1 = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0,0,0)   # 创建起点
dynamo_point_2 = Autodesk.DesignScript.Geometry.Point.ByCoordinates(10,10,0) # 创建终点
dynamo_line = Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint(dynamo_point_1, dynamo_point_2) # 传入参数起点和终点创建Dynamo线段
OUT = dynamo_line # 返回线段
```

下面尝试使用python脚本节点输出，并使用 **ToProtoType()** 将其转换为Dynamo几何类型，否则在Dynamo几何预览中将不可见。

```python
revit_xyz_1 = XYZ(0,0,0)
revit_xyz_2 = XYZ(10,10,0)
revit_line = Line.CreateBound(revit_xyz_1, revit_xyz_2)
OUT = revit_line.ToProtoType()
```
